### ISSUE TITLE
Request ECDSA certificates

### ISSUE THREAD

**Issue by jvehent** [xenolf/lego#119] opened 2016-02-10 19:54 UTC
Now that [Let's Encrypt supports ECDSA](https://twitter.com/letsencrypt/status/697504441075798016), it would be great if lego could generate ecdsa CSRs instead of RSA ones.

Most clients support P-256 and P-384 curves, with the former being more commonly used, so it would probably be a good default. That said, NIST recommends P-384 nowadays.

**Comment by mholt** [comment] 2016-02-10 19:56
I think this is a duplicate of #61.

**Closed by mholt** 2016-02-10 19:56 UTC

**Comment by xenolf** [comment] 2016-02-10 19:59
Yep, ECC support is in the [add-ecc-support](https://github.com/xenolf/lego/tree/add-ecc-support) branch. Currently we default to P-384.
