### ISSUE TITLE
HTTP/TLSAPN challenges are not disabled when --dns is set

### ISSUE THREAD

**Issue by fd0** [xenolf/lego#737] opened 2018-12-19 13:07 UTC
Hi,

I've noticed that setting `--dns exec` does not disable the HTTP and TLSAPN challenges, in contraction to the help:
```
$ ./lego --help
[...]
   --dns value                 Solve a DNS challenge using the specified provider. Disables all other challenges. Run 'lego dnshelp' for help on usage.
[...]
```

It still tries to listen on Port 443:
```
$  EXEC_PATH=/bin/true ./lego --server https://acme-staging-v02.api.letsencrypt.org/directory --dns exec --domains www.example.com run
2018/12/19 13:40:34 [INFO] [www.example.com] acme: Obtaining bundled SAN certificate
2018/12/19 13:40:35 [INFO] [www.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/qQewSSaytugQTkVMUhKfPxMRoYvJksovMyPxcMxtR_I
2018/12/19 13:40:35 [INFO] [www.example.com] acme: use tls-alpn-01 solver
2018/12/19 13:40:35 [INFO] [www.example.com] acme: Trying to solve TLS-ALPN-01
2018/12/19 13:40:35 Could not obtain certificates:
        acme: Error -> One or more domains had a problem:
[www.example.com] [www.example.com] acme: error presenting token: could not start HTTPS server for challenge -> listen tcp :443: bind: permission denied
```

I've worked around this for now using `--exclude` manually.

I suspect this was accidentally dropped in #700 when `cli_handlers.go` was deleted, here: https://github.com/xenolf/lego/commit/42941ccea6b431ebff203d4cb520991fb7b47951#diff-a9a3538169a51ba12c04f42346b4b1a7L148

I'll prepare a PR in a few minutes.

**Comment by ldez** [comment] 2018-12-19 13:15
duplicate of #730

**Closed by ldez** 2018-12-19 13:15 UTC
