### ISSUE TITLE
urface/cli deprecation warning

### ISSUE THREAD

**Issue by bfallik** [xenolf/lego#305] opened 2016-10-25 01:07 UTC
Saw this scary warning at the end of the lego run:

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

Doesn't seem to prevent lego from doing its job.

**Comment by xenolf** [comment] 2016-10-25 06:32
Hello there!

Which version of lego are you using?
Sounds a lot like #206 and #232.

**Comment by bfallik** [comment] 2016-10-25 12:38
```
$ lego --version
lego version 0.3.0
```

Yeah it probably is a dupe. Sorry for the noise.

**Comment by bfallik** [comment] 2016-10-25 12:38
I installed this using `brew` so I suppose their config is just out-of-date.

**Comment by xenolf** [comment] 2016-10-25 13:22
I didn't even know that homebrew had lego in it's repository :smile:

**Comment by bfallik** [comment] 2016-10-25 13:23
achievement unlocked!

**Comment by xenolf** [comment] 2016-11-02 15:07
Closing this as a dupe of #232

**Closed by xenolf** 2016-11-02 15:07 UTC
