### ISSUE TITLE
Listen IP/interface of lego unclear

### ISSUE THREAD

**Issue by sharpner** [xenolf/lego#39] opened 2015-12-04 10:12 UTC
Hi there!

I upgraded to v0.1 and now I am getting this error: 
```
2015/12/04 10:10:14 Could not create client:decode directory: invalid character '<' looking for beginning of value
```

I am using the following parameters:
```
lego --domains=mydomain.de -B 4096 --email="email@mydomain.de" -s "https://acme-v01.api.letsencrypt.org/" --path=/var/container/nginx/newcert/ --port 9999 run
```

Did something change? I tried using the existing keys and creating new ones, the error is still the same.

Thanks!

**Comment by sharpner** [comment] 2015-12-04 10:14
found it, you now need to use ```https://acme-v01.api.letsencrypt.org/directory```

**Comment by sharpner** [comment] 2015-12-04 10:39
So somethings fishy with version v0.1.0. 
I couldn't get it to work no matter what: 

```
/root/lego --domains=mydomain.de -B 4096 --email="n.wagensonner@manyminds.de"  --path=/var/container/nginx/cert/ --port 9999 run
2015/12/04 10:31:49 [INFO] acme: Obtaining bundled SAN certificate for mydomain.de
2015/12/04 10:31:50 [INFO] acme: Trying to solve TLS-SNI-01
2015/12/04 10:31:52 [codinator.de] Could not obtain certificates
	The server could not validate our request.
```

So I downgraded lego to #6a803c626577b215325830567f8131b985851cf6 and ran:
```
/root/lego.old --domains=mydomain.de -B 4096 --email="n.wagensonner@manyminds.de" -s "https://acme-v01.api.letsencrypt.org/directory" --path=/var/container/nginx/cert/ --port 9999 run
2015/12/04 10:32:11 [INFO] acme: Obtaining bundled SAN certificate for mydomain.de
2015/12/04 10:32:11 [INFO] acme: Trying to solve HTTP-01
2015/12/04 10:32:11 [INFO] Served key authentication
2015/12/04 10:32:13 The server validated our request
2015/12/04 10:32:13 [INFO] acme: Validations succeeded; requesting certificates
2015/12/04 10:32:15 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2015/12/04 10:32:15 [codinator.de] Server responded with a certificate.
```

with success. Is it my mistake?

**Comment by sharpner** [comment] 2015-12-04 10:42
okay I found the issue, lego now only listens to the public interface/ip of the given domain(/s).

**Comment by xenolf** [comment] 2015-12-04 14:19
Lego does have a fallback in case it can not bind to the public resolved IP [here](https://github.com/xenolf/lego/blob/master/acme/http_challenge.go#L103-L110). 
In that case it will bind to 0.0.0.0 - What I gather from the information you provided is that lego binds to the public IP but the challenge arrives on a different one?

**Comment by xenolf** [comment] 2015-12-04 14:36
Actually I see the problem now.
In your first example lego tries to solve the TLS-SNI challenge. You then roll back
to a commit which does not have that challenge implemented.
I had a look at the challenge and it seems like I forgot to add the fallback for that challenge :)

**Comment by sharpner** [comment] 2015-12-04 14:42
I am using a load balancer that proxies the acme-challenge via reverse proxy to a different machine. 
So therefore I would love to configure the listen ip as suggested in #40

**Comment by xenolf** [comment] 2015-12-04 14:45
Are you doing SSL termination at your load balancer?

**Comment by sharpner** [comment] 2015-12-05 12:51
yep! Did not know about the fallback though.

**Comment by mholt** [comment] 2015-12-05 16:40
Hmm, terminating SSL at the load balancer could be a problem because the TLS-SNI-01 challenge expects the TLS connection to be made with the machine that is completing the challenge, not a middle box.

**Comment by xenolf** [comment] 2015-12-05 16:56
Yes, SSL termination will definitely make the TLS-SNI challenge fail.
I need to think of an option to allow users to exclude challenges which are unsolvable in their environment using a command line switch. This would be the proper fix for this issue IMO.

**Comment by sharpner** [comment] 2015-12-08 08:44
yes that would help. A command line parameter ```--challenges``` could solve this issue right?

I would submit a PR but I am currently unsure on how the lego api changes, since there are so many refactoring PRs open :D

**Comment by mattr-google** [comment] 2015-12-27 02:58
I have this issue (ssl termination), would you accept a pull request adding a --challenges flag?  Right now this process either works for me or not depending on the order the challenges are evaluated.

**Comment by mholt** [comment] 2015-12-27 07:29
Changes are already in the works to allow you to specify which challenges can be used.

**Comment by xenolf** [comment] 2015-12-28 04:36
The "exclusion" of certain challenges is implemented in the [refactor-client](https://github.com/xenolf/lego/tree/refactor-client) branch. The new API of the lib is not 100% final tho :)

Please let me know if you have any questions / additions.

**Comment by mjrosencrantz** [comment] 2015-12-28 08:46
I have another issue.  I am forwarding to lego through a proxy, so I want lego to listen on localhost:9000 and then a proxy will forward traffic there.  Unfortunately what actually happens is that it listens on "domain:9000" which results in the real IP address, not localhost.  This causes the challenge validation to fail, but the listen succeeds so the fallback case where you listen on only port doesn't get hit.  I wonder if you could just change the port flag to be the full host:port string so the user could choose the behavior they want.

**Comment by flibustenet** [comment] 2015-12-28 08:51
+1 i thought it's the subject of this issue.
Why not listen on all interfaces ?

**Comment by mholt** [comment] 2015-12-28 19:45
@flibustenet (I assume by "interfaces" you mean all hosts for a port.) Because we (more accurately, I) received complaints when a user had other services already listening on all interfaces. So I changed it to bind to just the domain name.

**Comment by flibustenet** [comment] 2015-12-28 20:01
Yes i spoke about all hosts. It will be fine to have a flag to choose the host. Like said mjrosencrantz, the problem is that it silently fail and make it difficult to know why it doesn't work on some configuration.

**Comment by fenderle** [comment] 2015-12-29 00:02
+1 for being able to specify the bind ip for listen. in loadbalancer setups it is just not feasible to use the public domain name for that.

**Comment by xenolf** [comment] 2015-12-29 13:36
My take is to change the default to be `0.0.0.0` and to add a flag `--interface` so the user is able to restrict it himself.
Thoughts?

**Comment by flibustenet** [comment] 2015-12-29 18:18
@xenolf +1 with default to 0.0.0.0 it will help the first try success.

**Comment by mholt** [comment] 2015-12-29 18:54
Unless you have another program already bound to 0.0.0.0 on that port - then it will still have to try the other way.

**Comment by fenderle** [comment] 2015-12-29 19:38
I modified the refactoring branch to accept ip:port for the httpport flag. i find this to be a good solution since the user can choose to just specify the port (eg 80) or also specifiy the ip (eg 127.0.0.1:8080). however binding ipv4 and ipv6 could lead to problems with this scheme.

**Comment by xenolf** [comment] 2016-01-08 07:30
This landed today in the refactor-client branch.
The switches for HTTP and TLS now support host:port addresses. This also works for IPv6 with [ip]:port or any other scheme the [SplitHostPort](https://golang.org/pkg/net/#SplitHostPort) function supports.

**Comment by xenolf** [comment] 2016-01-08 07:30
Also lego will now default to listen on any interface :)

**Comment by sharpner** [comment] 2016-01-08 07:52
yay :-)

**Comment by flibustenet** [comment] 2016-01-08 08:34
Thanks !
You have an idea when you will merge this branch to master ?

**Comment by xenolf** [comment] 2016-01-09 01:19
The change landed in master.

**Closed by xenolf** 2016-01-09 01:19 UTC
