### ISSUE TITLE
go build on master branch is broken

### ISSUE THREAD

**Issue by prateekgogia** [xenolf/lego#547] opened 2018-05-25 04:45 UTC
I tried to build on master branch, go build fails - 

```
go build -v
github.com/xenolf/lego/providers/dns/dnsimple
# github.com/xenolf/lego/providers/dns/dnsimple
providers/dns/dnsimple/dnsimple.go:179:54: cannot use whoamiResponse.Data.Account.ID (type int) as type int64 in argument to strconv.FormatInt
```

**Comment by prateekgogia** [comment] 2018-05-25 04:53
#546 Fixes this issue.

**Comment by prateekgogia** [comment] 2018-05-25 06:29
Also build fails for ```tags/v0.4.1``` using the Dockerfile -
```
docker build -t lego . 
```
 throws this error -
```
# github.com/miekg/dns
go/src/github.com/miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
go/src/github.com/miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
```

This is because miekg/dns package requires go version > 1.9 to build. Refer https://github.com/miekg/dns/issues/686

Once, I updated go version to 1.9.2 in Dockerfile. It still fails with the following error - 

```
github.com/Azure/azure-sdk-for-go (download)
package github.com/Azure/azure-sdk-for-go/arm/dns: cannot find package "github.com/Azure/azure-sdk-for-go/arm/dns" in any of:
	/usr/local/go/src/github.com/Azure/azure-sdk-for-go/arm/dns (from $GOROOT)
	/go/src/github.com/Azure/azure-sdk-for-go/arm/dns (from $GOPATH)
```

This is because the `azure-sdk-for-go` repo has been updated and the `arm/dns` has been removed. Need to vendor this in this repo.

**Comment by shupp** [comment] 2018-05-29 22:52
You might try "go get -u -v ./..." on master.  I can't reproduce this this using 1.9.2 or 1.9.6.  You will see the first error on 1.8.x, though, and they just removed 1.8 testing from TravisCI as it's no longer supported.

**Comment by ldez** [comment] 2018-05-29 23:26
I'll close this issue, because it's resolve by #550.

**Closed by ldez** 2018-05-29 23:26 UTC
