### ISSUE TITLE
Problems installing on windows

### ISSUE THREAD

**Issue by lambada** [xenolf/lego#348] opened 2017-02-11 19:09 UTC
I'm trying to install from source, as the last release was a looong time ago and doesn't have all the recent bugfixes and features (CSR support!), but on Windows with a freshly installed git and go it seems like trying to install this project is a large task in itself.

Trying to install with go get seems to fail because something about Windows, go and git doesn't like how gopkg.in works - it seemingly can't handle the redirects that gopkg.in uses (see e.g. https://github.com/spf13/hugo/issues/297 for generic discussion for the same issue). While installing the dependencies manually as per the referenced issue gets further it seems like there are then further problems caused when go tries to install the dependencies (it's not failing because one of the dependencies [ini.v1] points to a git tag and it then seemingly wants to pull in further upstream changes for that dependency, which rather defeats the point of using a tag in the first place....)

As a quick fix could we get another binary release? I'd love to help debug this but I'm really not familiar with go package management techniques so I'm kind of flying blind here.

**Comment by lambada** [comment] 2017-02-11 19:14
Oh I forgot to provide an example of the error it gives me

```
# cd .; git clone https://gopkg.in/ini.v1 D:\gopath\src\gopkg.in\ini.v1
Cloning into 'D:\gopath\src\gopkg.in\ini.v1'...
fatal: The remote end hung up unexpectedly
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
package gopkg.in/ini.v1: exit status 128
```

Seems to treat a 301 redirect as an error...

**Comment by ldez** [comment] 2018-09-22 00:31
The problem is fixed now.

**Closed by ldez** 2018-09-22 00:31 UTC
