### ISSUE TITLE
builds break against recent dnsimple

### ISSUE THREAD

**Issue by dhduvall** [xenolf/lego#724] opened 2018-12-01 16:28 UTC
As of dnsimple/dnsimple-go@9f1e8e5, I get the following error when building:

    .../providers/dns/dnsimple/dnsimple.go:74:31: undefined: dnsimple.NewOauthTokenCredentials

having imported `github.com/xenolf/lego/providers/dns`. It looks like they deliberately got rid of their built-in OAuth handling, punting that to `golang.org/x/oauth2`, and not keeping this function around for convenience.

**Comment by ldez** [comment] 2018-12-01 16:55
Hello, the issue is already fixed inside my PR #700.

https://github.com/xenolf/lego/pull/700/commits/c4c574c241553fda8b768ce942245b34ceceada6

**Closed** 2018-12-06 21:50 UTC
Labels: area/dnsprovider, enhancement
