### ISSUE TITLE
tls flag

### ISSUE THREAD

**Issue by mizutechvoip** [xenolf/lego#625] opened 2018-08-26 09:31 UTC
The --tls command line option is missing from version 1.0.0 and 1.0.1.

Console error message when the --tls option is set:

> Incorrect Usage. flag provided but not defined: -tls

The flag was present in version 0.5.0. It should be added back or the documentation (README.md) changed accordingly.

**Comment by ldez** [comment] 2018-09-08 13:34
Duplicate of #583

Attention to the order of the arguments:

- **INVALID**
```shell
# INVALID
./lego run --tls ":80" -m foo@barcom
```

- **VALID**
```shell
# VALID
./lego --tls ":80" -m foo@barcom run
```

**Closed by ldez** 2018-09-08 13:34 UTC
Labels: area/cli, question
