### ISSUE TITLE
DEPRECATED Action signature.  Must be `cli.ActionFunc`

### ISSUE THREAD

**Issue by clandmeter** [xenolf/lego#232] opened 2016-06-15 20:56 UTC
When running lego cli, im getting the following msg:

DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by xenolf** [comment] 2016-06-15 23:04
Thanks for reporting!

Did you compile yourself or did you use a pre-built binary?
This seems to be a duplicate of #206 and I already changed the signatures of the CLI handlers back then.

**Comment by clandmeter** [comment] 2016-06-16 20:00
I maintain [lego](http://git.alpinelinux.org/cgit/aports/tree/testing/lego/APKBUILD) for Alpine Linux which is musl libc based, so we have to compile it our self. 
Strange, seems my search magic has failed me, I applied the patch and it works OK now.

Thanks!

**Comment by xenolf** [comment] 2016-06-17 07:06
Thank you for your work on maintaining for alpine, much appreciated :D
Glad you got it sorted :) I'm going to close this, feel free to re-open this issue if there are further questions or problems.

**Closed** 2016-06-17 20:54 UTC
